name: PriorMDM
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.9.24=py38h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.3=h5eee18b_3
  - numpy=1.23.4=py38h14f4228_0
  - numpy-base=1.23.4=py38h31eccc5_0
  - openssl=1.1.1s=h7f8727e_0
  - pip=22.2.2=py38h06a4308_0
  - python=3.8.15=h7a1cb2a_2
  - readline=8.2=h5eee18b_0
  - setuptools=65.5.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.0=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - attrs==22.1.0
    - beautifulsoup4==4.11.1
    - blis==0.7.9
    - blobfile==2.0.0
    - catalogue==2.0.8
    - charset-normalizer==2.1.1
    - chumpy==0.70
    - clearml==1.8.1
    - click==8.1.3
    - confection==0.0.3
    - contourpy==1.0.6
    - cycler==0.11.0
    - cymem==2.0.7
    - einops==0.6.0
    - filelock==3.8.0
    - fonttools==4.38.0
    - freetype-py==2.3.0
    - ftfy==6.1.1
    - furl==2.1.3
    - gdown==4.6.0
    - h5py==3.8.0
    - huggingface-hub==0.11.1
    - idna==3.4
    - imageio==2.27.0
    - importlib-resources==5.10.0
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.17.1
    - kiwisolver==1.4.4
    - langcodes==3.3.0
    - lxml==4.9.1
    - markupsafe==2.1.1
    - matplotlib==3.1.3
    - more-itertools==9.0.0
    - murmurhash==1.0.9
    - networkx==3.1
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-htop==1.0.5
    - orderedmultidict==1.0.1
    - packaging==21.3
    - pandas==1.5.2
    - pathlib2==2.3.7.post1
    - pathy==0.10.0
    - pillow==9.3.0
    - pkgutil-resolve-name==1.3.10
    - plotly==5.11.0
    - preshed==3.0.8
    - psutil==5.9.4
    - pycryptodomex==3.16.0
    - pydantic==1.10.2
    - pyglet==2.0.5
    - pyjwt==2.4.0
    - pyopengl==3.1.0
    - pyparsing==3.0.9
    - pyrender==0.1.45
    - pyrsistent==0.19.2
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - pytz==2022.6
    - pyyaml==6.0
    - regex==2022.10.31
    - requests==2.28.1
    - scipy==1.9.3
    - smart-open==5.2.1
    - soupsieve==2.3.2.post1
    - spacy==3.4.3
    - spacy-legacy==3.0.10
    - spacy-loggers==1.0.3
    - srsly==2.4.5
    - tenacity==8.1.0
    - termcolor==2.1.1
    - thinc==8.1.5
    - tokenizers==0.13.2
    - torch==1.13.0
    - torchvision==0.14.0
    - tqdm==4.64.1
    - transformers==4.25.1
    - trimesh==3.18.1
    - typer==0.7.0
    - typing-extensions==4.4.0
    - urllib3==1.26.13
    - wasabi==0.10.1
    - wcwidth==0.2.5
    - zipp==3.11.0
prefix: PriorMDM-venv
